### PR TITLE
fix: update link to runtime-compat-data

### LINKED ISSUE #56: Broken Link
The first link on `https://runtime-compat.unjs.io` points to `https://github.com/unjs/runtime-compat-data`, which 404s. This should either link to `https://github.com/unjs/runtime-compat` (this repo) or `https://github.com/unjs/runtime-compat/tree/main/packages/runtime-compat-data` (the applicable subdir).

### PR DESCRIPTION
**Pull request by CanadaHonk**
### 🔗 Linked issue

Fixes #56.

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fixes broken link to runtime-compat-data (#56).

### 📝 Checklist

- [X] I have linked an issue or discussion.

### CODE REVIEW

**Review by ascorbic — APPROVED** [review]

File: apps/website/src/app.vue [hunk 1]
```diff
@@ -6,7 +6,7 @@
       </h2>
       <p class="text-md text-slate-600 max-w-4xl">
         Display APIs compatibility across different JavaScript runtimes. The data is retrieved from <ExternalLink
-          href="https://github.com/unjs/runtime-compat-data">
+          href="https://github.com/unjs/runtime-compat/tree/main/packages/runtime-compat-data">
```
Comment (pi0) [inline apps/website/src/app.vue:9]: Do we want to directly link to a specific package if gen scripts are outside? @ascorbic
